
                <ul class="ca-menu">
                    <li>
                        <a href="/mychem/cpanel/conf">
                            <span class="ca-icon" id="img1"></span>
                            <div class="ca-content">
                                <h2 class="ca-main">Управление конфиренциями</h2>
                                <h3 class="ca-sub">удхту</h3>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="/mychem/cpanel/udhtu-folder">
                            <span class="ca-icon">Ггг</span>
                            <div class="ca-content">
                                <h2 class="ca-main">Управление сайтом</h2>
                                <h3 class="ca-sub">Professionals in action</h3>
                            </div>
                        </a>
                    </li>
                                    
                </ul>
                <?=var_dump($action)?>