
			<center>
			<img  width="100px" height="100px" src="">
				<p><b>Факультет технології неорганічних речовин:</b><button id="create-user">Добавить сотрудника</button><br></p>
				</center>




<div id="dialog-form" title="Добавить сотрудника">
  <form action="POST" id="fm_create_otdel_worker">
	<fieldset>

	 




	  <label for="mus_login">Логин</label>
		<input type="text" name="mus_login" id="mus_login" style="display:inline;" class="text ui-widget-content ui-corner-all">
	 	<div id="get_mus_login">Получить сведенея</div>

	 	
	 	<label for="fio">Оригинальное ФИО</label>
		<input type="text" readonly id="fio" name="fio"   class="text ui-widget-content ui-corner-all">


	 	<label for="fio_layout">ФИО Можете изменить на подмаску при надобности</label>
		<input type="text" name="fio_layout" id="fio_layout"   class="text ui-widget-content ui-corner-all">



	
		<div id="mu_main_job" style="display:inline;"> 
			<label >Должность</label>
			<select class="form_field_select" id="mu_main_job" name="mu_main_job">		
				<option selected disabled data="option_main_job_0" value=0 >Зробіть вибір...</option>
					<?php foreach($main_job as $key => $value):
						echo '<option data="option_degree_'.$value['id'].'" value="'.$value['id'].'">'.$value['name'].'</option>';			
					ENDFOREACH?>
			</select></div>	
	<label for="job_comment">job_comment</label>
			<input type="text" name="job_comment" id="job_comment"  class="text ui-widget-content ui-corner-all">

		<div id="mu_degree">
			<label >Посада</label>
			<select class="form_field_select"  name="mu_degree">		
				<option selected disabled data="option_degree_0" value=0 >Зробіть вибір...</option>
					<?php foreach($degree as $key => $value):
						echo '<option data="option_degree_'.$value['id'].'" value="'.$value['id'].'">'.$value['name'].'</option>';			
					ENDFOREACH?>
			</select></div>	
		<div id="mu_uch_stepen">
			<label >Науковий ступінь, звання</label>
			<select class="form_field_select"  name="mu_uch_stepen">		
			<option selected disabled data="option_uch_stepen_0" value=0  >Зробіть вибір...</option>
					<?php foreach($uch_stepen as $key => $value):
						echo '<option data="option_uch_stepen_'.$value['id'].'" value="'.$value['id'].'">'.$value['name'].'</option>';	
					ENDFOREACH?>
		</select>
		</div>



		<label for="email">Email</label>
		<input type="text" name="email" id="email" readonly class="text ui-widget-content ui-corner-all">
	 	<label for="tel">Телефон</label>
		<input type="text" name="tel" id="tel" readonly class="text ui-widget-content ui-corner-all"> 
		

		<label for="about">about</label>
		<textarea  name="about" id="about"  class="text ui-widget-content ui-corner-all"></textarea>

		<label for="file">Фото</label>
		<input type="file" name="file">

	  <!-- Allow form submission with keyboard without duplicating the dialog button -->
	   <input type="hidden" id="id_user" name="id_user" value="0">

	  <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
	</fieldset>
  </form>
</div>
 
 
<div id="users-contain" class="ui-widget">
  <h1>Текушие сотрудники:</h1>
  <table id="users" class="ui-widget ui-widget-content">
	<thead>
	  <tr class="ui-widget-header ">
		<th>Фото</th>
		<th>Ф.И.О.</th>
		<th>Должность</th>

		<th>Контакты</th>
		<th>Подробнее</th>
	   
	  </tr>
	</thead>
	<tbody>
	  <tr>
		<td><img  width="100px" height="100px" src=""></td>
		<td>Фамилия Имя Очество</td>
		<td>Декан <br>(И\О)</td>		
		<td>Контакты</td>
		<td><button>Подробнее</button></td>
	  </tr>
	</tbody>
  </table>
</div>
















				<p><b>Доступный контент к наполнению\изменению</b><br></p>

