<?php if (($params['himsovrtehn']== 'all') || ($params['fuel']== 'all')): ?>
    
<?php  
    switch (key($params)) {
        case 'fuel':
            echo "<center><h2>Данные по зареганным в фуел</h2></center>";
            foreach ($titlePublic as $key => $value): ?>
               

            <div class="box_conf">   
            <h2 class="punct_conf"><?=$value['title_public']?></h2>
            
            <div class="about_conf">               
                <div class="about_conf_menu"><a href="/mychem/activconf/fuel/<?=$value['id']?>">Редaктировать</a></div>
                <div class="about_conf_menu"><a href="/mychem/activconf/fuel/all">Удалить</a></div>
                 <!-- <div class="about_conf_menu">Снять с регистрации</div> -->
                <div class="clear"></div>                   
            </div>



            <?php ENDFOREACH; 
            break;
        case 'himsovrtehn':
            echo "<center><h2>Данные по зареганным в Химсовртех</h2></center>";
                        foreach ($titlePublic as $key => $value): ?>
               

            <div class="box_conf">   
            <h2 class="punct_conf"><?=$value['title_public']?></h2>
            
            <div class="about_conf">               
                <div class="about_conf_menu"><a href="/mychem/activconf/himsovrtehn/<?=$value['id']?>" >Редоктировать</a></div>
                <div class="about_conf_menu"><a href="/mychem/activconf/himsovrtehn/all">Удалить</a></div>
                 <!-- <div class="about_conf_menu">Снять с регистрации</div> -->
                <div class="clear"></div>                   
            </div>



            <?php ENDFOREACH; 

            break;
        

    }

 ?>

    

<?php ENDIF; ?>





    <?php 
       if (is_numeric($params['himsovrtehn']) || is_numeric($params['fuel'])):                    
                  var_dump($conf_data);
               foreach ($conf_data as $key => $data_value):
               

         
     ?>
    
   <div id="mu_reg_lang">
    <button  class="button_lang">
        <img width="30px" height="30px" src="/public/img/mychem/conference/form/ukr.jpg" alt="ukr" >
    </button>
    <button class="button_lang">
        <img width="30px" height="30px" src="/public/img/mychem/conference/form/rus.jpg" alt="rus">
    </button>
    <button class="button_lang">
        <img width="30px" height="30px" src="/public/img/mychem/conference/form/eng.jpg" alt="eng" >
    </button>   

</div>
<div id="mu_registred" style="float:none;">
    <form  method="post" id="mu_conf_reg"> 
        <?php  echo "<h2 style='color:red'>".$_COOKIE['err_reg']."</h2>"; ?>
        <hr>
        <div id="mu_organization">
            <label >Назва організації</label>
            <input class="form_field" type="text" name="mu_organization" value="<?=$data_value['organization']?>">
        </div>
        <div id="mu_degree">
            <label >Посада</label>
            <select class="form_field_select"  name="mu_degree">        
                <option selected disabled data="option_degree_0" value=0 >Зробіть вибір...</option>
                    <?php foreach($degree as $key => $value):
                         if($data_value['mu_degree'] ==  $value['id']){
                        echo '<option selected data="option_degree_'.$value['id'].'" value="'.$value['id'].'">'.$value['value'].'</option>';  
                        }else{
                            echo '<option data="option_degree_'.$value['id'].'" value="'.$value['id'].'">'.$value['value'].'</option>';  
                        }       
                    ENDFOREACH?>
            </select></div> 
        <div id="mu_uch_stepen">
            <label >Науковий ступінь, звання</label>
            <select class="form_field_select"  name="mu_uch_stepen">        
            <option selected disabled data="option_uch_stepen_0" value=0  >Зробіть вибір...</option>
                    <?php foreach($uch_stepen as $key => $value):
                     if($data_value['mu_uch_stepen'] ==  $value['id']){
                        echo '<option selected data="option_uch_stepen_'.$value['id'].'" value="'.$value['id'].'">'.$value['value'].'</option>'; 
                    }else{
                          echo '<option data="option_uch_stepen_'.$value['id'].'" value="'.$value['id'].'">'.$value['value'].'</option>'; 
                    }
                    ENDFOREACH?>
        </select>
        </div>      
        <div id="mu_topic_conf">
            <label >Тематичні напрямки</label>
            <select class="form_field_select"  name="mu_topic_conf">
                <option selected disabled  data="option_topic_conf_0" value="0" >Зробіть вибір...</option>
                    <?php foreach($topic_conf as $key => $value):
                        if($data_value['mu_topic_conf'] ==  $value['id']){
                        echo '<option selected data="option_topic_conf_'.$value['id'].'" value="'.$value['id'].'">'.$value['value'].'</option>';     
                        }else{
                              echo '<option data="option_topic_conf_'.$value['id'].'" value="'.$value['id'].'">'.$value['value'].'</option>';     
                         }
                    ENDFOREACH?>
            </select>
        </div>
        <div id="mu_type_presentation">
            <label >Форма доповіді</label>
            <select class="form_field_select"  name="mu_type_presentation">     
                <option  disabled data="option_type_presentation_0" value="0" >Зробіть вибір...</option>
                    <?php foreach($type_presentation as $key => $value):
                        if($data_value['mu_type_presentation'] ==  $value['id']){
                        echo '<option selected data="option_type_presentation_'.$value['id'].'" value="'.$value['id'].'">'.$value['value'].'</option>'; 
                        }else{
                             echo '<option  data="option_type_presentation_'.$value['id'].'" value="'.$value['id'].'">'.$value['value'].'</option>';
                        }     
                    ENDFOREACH?>
            </select></div> 
         <div id="mu_title_public">
            <label >Назва доповіді</label>
            <input class="form_field" type="text" name="mu_title_public" value="<?=$data_value['title_public']?>">
        </div>



        <div id="mu_co_autor">
            <label >Соавторы</label>          
            <a href="#" class="paulund_modal">Добавить</a>
            
        </div>



















         <?php if(key($params) == 'fuel'): ?>  
        <div id="mu_abstracts">     
            <label >Анотація (200 слів)</label>
            <textarea  id="text_area" rows="3" class="form_field" cols="45" name="mu_abstracts"><?=$value['abstracts']?><?=$data_value['abstracts']?></textarea>
        </div>           
        <div  id="mu_party">
            <label>Участь у фуршеті – 23 травня</label>
            <input class="form_field_che" type="checkbox" name="mu_party" value="1"  
            <?php if($data_value['party'] == 1) 
                echo "checked";
            ?>>
        </div>  
        <div id="mu_training_courses">
            <label >Курси підвищення кваліфікації</label>
            <input class="form_field_che" type="checkbox" name="mu_training_courses" value="1" 
            <?php if($data_value['advanced_training_courses'] == 1) 
                echo "checked";
            ?>>
            <p><input type="hidden" name="conf" value="1"></p>
             <p><input type="hidden" name="id_work" value="<?=$data_value['id']?>"></p>
        </div>  
        <?php ENDIF;?>
         <?php if(key($params) == 'himsovrtehn'): ?>  
            <p><input type="hidden" name="conf" value="2"></p>
             <p><input type="hidden" name="id_work" value="<?=$data_value['id']?>"></p>
            
          <div><label>Потрібность у готелі</label><input class="form_field_che"  type="checkbox" name="mu_hotel" value="1"  <?php if($data_value['hotel'] == 1) 
                echo "checked";
            ?>></div>   

         <?php ENDIF;?>

        <?php //<div><label>Потрібность у готелі</label><input class="form_field" type="checkbox" name="mu_hotel" value="1"></div> ?><div style="margin:25px 0 0 0">
        <center>
            <p><input id="button_reg_conf" type="submit" value="Подати заявку на участь"></p>           
        </center>
    </div>
    </form> 
    <?php
    //<div style="margin:25px 0 0 0">
    //  <center>
    //      <button id="button_reg_conf">&nbsp;Зареєструватися&nbsp;</button>
    //  </center>
    //</div> ?> 
</div>


<?php 
ENDFOREACH;

ENDIF; ?>










<?php if (!$params):
    
?>

         <div class="box_conf">   
            <a href="/mychem/activconf/fuel/all"  ><h2 class="punct_conf">Прогрес в технології переробки горючих копалин та хімотології паливно-мастильних матеріалів</h2></a>
            
            <div class="about_conf">               
             <!--    <div class="about_conf_menu"><a href="http://udhtu.com.ua/conference/index.php?p=8"  target="_blank">Інформація</a></div>
                <div class="about_conf_menu"><a href="/mychem/activconf/fuel/all">Проверка подавших заявку</a></div>
                 <div class="about_conf_menu">Снять с регистрации</div> -->
                <div class="clear"></div>                   
            </div>
                 

             <a href="/mychem/activconf/himsovrtehn/all"  > <h2 class="punct_conf">Хімія та сучасні технології</h2></a>
           <!--  <div class="about_conf">               
                <div class="about_conf_menu"><a href="http://udhtu.com.ua/conference/index.php?p=26"  target="_blank">Інформація</a></div>
                <div class="about_conf_menu"><a href="/mychem/activconf/himsovrtehn/all">Проверка подавших заявку</a></div>
               <div class="about_conf_menu">Снять с регистрации</div> -->
                <div class="clear"></div>                   
            </div>


<?php ENDIF; ?>


<?php
 if (($params['himsovrtehn'] == 'done') || ($params['fuel'] == 'done')):
    echo "<center><div style='font-size:18px;font-weight:bold;color:green;'>Изменение данных прошло успешно</div></center>";
     echo "<a href='http://udhtu.waterh.net/mychem/activconf'>Повернутися до вибору конференцій</a>";
    ?>




<?php ENDIF; ?>



