
                <ul class="ca-menu">
                    <li>
                        <a href="/mychem/activconf">
                            <span class="ca-icon" id="img1"></span>
                            <div class="ca-content">
                                <h2 class="ca-main">Ваши конференции</h2>
                                <h3 class="ca-sub">удхту</h3>
                            </div>
                        </a>
                    </li>
                                             
                </ul>