<div class="autForm">
	<div class="errorAuth"><?=$errorAuth?></div>
	<form method="POST" name="aut_form" action="login">
		<p><label for="login">e-mail</label></p>
		<p><input class="formField" type="text" name="login" id="login"></p>
		<p><label for="password">Пароль</label></p>
		<p><input class="formField" type="password" name="password" id="password"></p>
		<center><p><input class="btnLogin" type="submit" value=" Увійти "></p></center>
	</form>
	<center><p><a href="/reset">Забули пароль?</a></p></center>
</div>
<img style="float:right;" src="/public/img/front/enter.png">