<?php 



if(!empty($content['text'])){

	
/*
	?>	
<div class="head-fak">		
	<img src="<?=$otdel_staff[0]['about'] ?>">
	<h2><?=$content['name_fak'];?></h2>
	<div class="contact-fak">
	<?php 
		foreach ($contact as $key => $value) {
			echo "<p>".$value['label'].': '.$value['data']."</p>";
		}
	?>
			
		<div class="soc-con-fak" style="display:none">
			<a href="http://vk.com/club69358513">
				<img src="http://udhtu.com.ua/userfiles/image/vkontaktu.png" alt="">
			</a>
			<a href="https://www.facebook.com/TS.UDHTU">
				<img src="http://udhtu.com.ua/userfiles/image/facebook.png"  alt="">
			</a>
			<div class="news-fak">Новости</div>
		</div>
	</div>
	
</div>
	
		    <?php 
		    if($otdel_staff){
		    	echo '<div id="fakultet" class="accordion">  <ol>';
		    	$slide =1;
		    	$vp = 1;

		    	foreach ($otdel_staff as $key => $value) {
		    		if($vp != $value['porydok_slide']){
		    			echo "</figcaption>	</figure> </div> </li>";
		    			$vp +1;
		    		}


		    		if($value['porydok_slide'] == $slide){
		    			echo "<li>";
		    			echo "<h2><span>".$value['short_data']."</span></h2>";
		    			echo "<div>";
		    			echo "<figure>";
		    			echo '<img src="'.$value["img"].'" alt="image" />';
		    			echo "<figcaption>";		    		
		    			$slide+=1;
		    			$vp = $value['porydok_slide'];
		    			echo "<p>".$value['data']." ".mb_strtolower($otdel_staff['short_name'], 'UTF-8').'</p> <p>'.$value['last_name'].' '.$value['name'].' '.$value['middle_name']."</p>";
		    			continue;
		    		}
		    		if($value['porydok_view'] == 2)
		    			echo $value['data'];
		    		else	
		    			echo ", ".mb_strtolower($value['data'], 'UTF-8');





		    	}



		    	echo '</ol>	</div>';
}
		    */ ?>

			



<div> 
<?=$content['text'];?>
 </div>
 <?php
 /*
				<div id="rg-gallery" class="rg-gallery">
					<div class="rg-thumbs">
						<!-- Elastislide Carousel Thumbnail Viewer -->
						<div class="es-carousel-wrapper">
							<div class="es-nav">
								<span class="es-nav-prev">Previous</span>
								<span class="es-nav-next">Next</span>
							</div>
							<div class="es-carousel">
								<ul>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/1.jpg" data-large="/public/img/front/slider_fak/1.jpg" alt="image01" data-description="From off a hill whose concave womb reworded" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/2.jpg" data-large="/public/img/front/slider_fak/2.jpg" alt="image02" data-description="A plaintful story from a sistering vale" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/3.jpg" data-large="/public/img/front/slider_fak/3.jpg" alt="image03" data-description="A plaintful story from a sistering vale" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/4.jpg" data-large="/public/img/front/slider_fak/4.jpg" alt="image04" data-description="My spirits to attend this double voice accorded" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/5.jpg" data-large="/public/img/front/slider_fak/5.jpg" alt="image05" data-description="And down I laid to list the sad-tuned tale" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/6.jpg" data-large="/public/img/front/slider_fak/6.jpg" alt="image06" data-description="Ere long espied a fickle maid full pale" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/7.jpg" data-large="/public/img/front/slider_fak/7.jpg" alt="image07" data-description="Tearing of papers, breaking rings a-twain" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/8.jpg" data-large="/public/img/front/slider_fak/8.jpg" alt="image08" data-description="Storming her world with sorrow's wind and rain" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/9.jpg" data-large="/public/img/front/slider_fak/9.jpg" alt="image09" data-description="Upon her head a platted hive of straw" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/10.jpg" data-large="/public/img/front/slider_fak/10.jpg" alt="image10" data-description="Which fortified her visage from the sun" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/11.jpg" data-large="/public/img/front/slider_fak/11.jpg" alt="image11" data-description="Whereon the thought might think sometime it saw" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/12.jpg" data-large="/public/img/front/slider_fak/12.jpg" alt="image12" data-description="The carcass of beauty spent and done" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/13.jpg" data-large="/public/img/front/slider_fak/13.jpg" alt="image13" data-description="Time had not scythed all that youth begun" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/14.jpg" data-large="/public/img/front/slider_fak/14.jpg" alt="image14" data-description="Nor youth all quit; but, spite of heaven's fell rage" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/15.jpg" data-large="/public/img/front/slider_fak/15.jpg" alt="image15" data-description="Some beauty peep'd through lattice of sear'd age" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/16.jpg" data-large="/public/img/front/slider_fak/16.jpg" alt="image16" data-description="Oft did she heave her napkin to her eyne" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/17.jpg" data-large="/public/img/front/slider_fak/17.jpg" alt="image17" data-description="Which on it had conceited characters" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/18.jpg" data-large="/public/img/front/slider_fak/18.jpg" alt="image18" data-description="Laundering the silken figures in the brine" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/19.jpg" data-large="/public/img/front/slider_fak/19.jpg" alt="image19" data-description="That season'd woe had pelleted in tears" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/20.jpg" data-large="/public/img/front/slider_fak/20.jpg" alt="image20" data-description="And often reading what contents it bears" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/21.jpg" data-large="/public/img/front/slider_fak/21.jpg" alt="image21" data-description="As often shrieking undistinguish'd woe" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/22.jpg" data-large="/public/img/front/slider_fak/22.jpg" alt="image22" data-description="In clamours of all size, both high and low" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/23.jpg" data-large="/public/img/front/slider_fak/23.jpg" alt="image23" data-description="Sometimes her levell'd eyes their carriage ride" /></a></li>
									<li><a href="#"><img src="/public/img/front/slider_fak/thumbs/24.jpg" data-large="/public/img/front/slider_fak/24.jpg" alt="image24" data-description="As they did battery to the spheres intend" /></a></li>
								</ul>
							</div>
						</div>
						<!-- End Elastislide Carousel Thumbnail Viewer -->
					</div><!-- rg-thumbs -->
				</div><!-- rg-gallery -->
*/
	}


?>



