<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" type="text/css" href="/public/css/main.css">
  <script type="text/javascript" src="/public/js/jQuery-v1.8.2.js"></script>   
  <script type="text/javascript" src="/public/js/jquery.cookie.js"></script>
  <script type="text/javascript" src="/public/js/front/jq_front.js"></script>

  <title>Мой суперпроект</title>
	
</head>




 <body> 	
	
		






  <?=$content?>











  </body>
</html>
