<?php  
use Front\Model\GetContent;
$GetContent = new GetContent();


    //формирование масивов  позхиционніх меню
    $blockMenu = $GetContent->getBlockMenu($_SESSION['lang']);



    for ($i=0; $i < count($blockMenu) ; $i++) { 
          switch ($blockMenu[$i]['type_position']) {
            case 'left':
              //asort($fruits, SORT_NUMERIC)
              //echo $blockMenu[$i]['porydok'] ;
              $blockLeftMenu[$i] = $blockMenu[$i];

              break;
            case 'top':
              //asort($fruits, SORT_NUMERIC)
              //echo $blockMenu[$i]['porydok'] ;
              $blockTopMenu[$i] = $blockMenu[$i];
              break;
            case 'right':
              //echo 'right';
              //echo $blockMenu[$i]['porydok'] ;
              $blockRightMenu[$i] = $blockMenu[$i];
              break;
            case 'center':
              //echo 'center';
              //echo $blockMenu[$i]['porydok'] ;
              $blockCenterMenu[$i] = $blockMenu[$i];
              break;            
            default:
              # code...
              break;
          }         
        }

        
           usort($blockTopMenu, "cmp");













    if($blockTopMenu){
      echo ' <ul class="l-menu" style="padding:0;margin:0;">';
      foreach ($blockTopMenu as $key => $value) { 
         $active_lm='';
        if($_SESSION['active_block'] == $value["url_title"] )
           $active_lm = 'style="display:block;"';
        if($value['type_content']=='block'){      
          echo ' <li class="menu"> <ul> ';        
          echo ' <li  style="display:block;width:auto;" class="button"></li> <li class="dropdown" style="display:block;width:auto;" '.$active_lm.'><ul>';
          foreach ($blockTopMenu as $key => $value1) {
            $active_lm='';
            if($_SESSION['active_block'] == $value["url_title"] && $_SESSION['active_subblock'] == $value1["url_title"] )
                $active_lm = '';
            if($value1['path'] == $value["path"] && $value1['type_content'] != 'block' ){
              if($value1['url'] == '#'){
                echo ' <li style="float:left;"  class="subblock_c vline'.$active_lm.'" path='.$value1["path"].'/'.$value1["id_mtt"].'><a  href=/'.$value["url_title"].'/'.$value1["url_title"].'>'.$value1["name"].'</a></li> ';
              }else{
                echo ' <li  style="float:left;"  class="vline'.$active_lm.'"><a href=/'.$value["url_title"].'/'.$value1["url_title"].'>'.$value1["name"].'</a></li> ';
                //echo ' <div class="center-punct" class="pullDown" ><div class="punct_menu_lvl_1 slideUp ">'.$value1["name"].'</div></div>';
               }
            }
          }
          echo ' </ul></li></ul></li>';
        }
      }
      echo ' </ul>';
    }



















/*


    if($blockTopMenu){
      echo ' <ul class="l-menu" style="padding:0;margin:0;">';
      foreach ($blockTopMenu as $key => $value) {          
        if($value['type_content']=='block'){      
          echo ' <li class="menu" > <ul> ';        
          echo '<li style="display:block;"><ul class="tete">';
          foreach ($blockTopMenu as $key => $value1) {
            if($value1['path'] == $value["path"] && $value1['type_content'] != 'block' ){
              if($value1['url'] == '#'){
                echo ' <li style="float:left;"  class="subblock_c vline" path='.$value1["path"].'/'.$value1["id_mtt"].'><a onclick="return false" href='.$value["url_title"].'/'.$value1["url_title"].'>'.$value1["name"].'</a></li> ';
              }else{
                echo ' <li class="vline" style="float:left;"><a href=/'.$value["url_title"].'/'.$value1["url_title"].'>'.$value1["name"].'</a></li> ';
                //echo ' <div class="center-punct" class="pullDown" ><div class="punct_menu_lvl_1 slideUp ">'.$value1["name"].'</div></div>';
               }
            }
          }
          echo ' </ul></li></ul></li>';
        }
      }
      echo ' </ul>';
    }

*/


















?>