<?php header('Content-type: text/html; charset=utf-8'); ?>
<!doctype html>
<html>
<head>
 
 
  <link rel="stylesheet" type="text/css" href="/public/css/mychem/mychem.css">  


         




  <title>УДХТУ - conference</title>

<style type="text/css">





#cropContainerEyecandy {
    width: 500px;
    height: 375px;
    position: relative;
    border: 1px solid #ccc;
        }




</style>






</head>


  <body>


	<div id="container">
		<div id="main">
			<div id="header">
				<center><a href="http://udhtu.com.ua" target="_blank">Український державний хіміко-технологічний університет</a></center>
			</div>	
	

			<div id="rightMenu">							
					<?php // include '/module/mychem/src/mychem/form/form_reg_fuel.phtml';?>
					   
    	<div class="rmenu" >
    		<ul >    	
    			<li><a href="/logout">EXIT</a></li>
    			
    		</ul>
    		
    	</div> 					
				</div>
		
				
			


				
			</div>			
			<div id="content">	
			




			


<?=$content?>








</div> <!-- /content -->
			<div id="footer">				

			</div> <!-- /end footer -->			
		</div>
	</div>


  <script type="text/javascript" src="/public/js/jQuery-v1.8.2.js"></script>
    <script type="text/javascript" src="/public/js/jq_main.js"></script> 
    <script type="text/javascript" src="/public/js/mychem/jq_mychem.js"></script>
    <script type="text/javascript" src="/public/js/mychem/mu_jq_main.js"></script>     
      <script type="text/javascript" src="/public/js/jquery.cookie.js"></script>
  <script type="text/javascript" src="/public/js/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="/public/js/mychem/jquery.paulund_modal_box.js"></script>
    <script type="text/javascript" src="/public/js/jquery-ui.js"></script>





    </body>

 
</html>
