<div id="mainProfile">
	<div id="mainDataProfile" style="margin-left:25px;">
<div style="float:left;"><img width="200px" height="200px" src="/public/img/mychem/conference/form/ukr.jpg" alt="ukr" ></div>
      <div style="margin-left:225px"> 
      	 <p>Основные даные Фио </p>
        <p>Основные даные Год рождения </p>
         <p>Основные даные чето еше</p>
        <p>Основные даные статус </p>
    </div>
    	<div class="clear"></div>
    </div>
    <div id="switchMenuInfo">
    	<div class="switch" >
    		<ul >
    			<li>Личные данные</li>
    			<li>Данные о работе</li>
    			<li>Данные по учебе </li>
    			<li>Итд</li>
    			<li>итп</li>
    		</ul>
    		<div class="clear"></div>
    	</div>
    		<div class="clear"></div>
    	<div class="infoUser">
 <p>Основные даные чето еше</p>
      <div>
           <form action="" method="post" enctype="multipart/form-data">
             <input type="file" id='file' onchange="previewFile()" name="filename"><br>
              
   
      <input type="submit" value="Загрузить"><br>
      </form>




      </div>

    </div>







    </div>  




    </div>






