
                <ul class="ca-menu">
                    <li>
                        <a href="/mychem/conference">
                            <span class="ca-icon" id="img1"></span>
                            <div class="ca-content">
                                <h2 class="ca-main">Конференции</h2>
                                <h3 class="ca-sub">удхту</h3>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="/mychem/profile">
                            <span class="ca-icon">Ггг</span>
                            <div class="ca-content">
                                <h2 class="ca-main">Профиль</h2>
                                <h3 class="ca-sub">Professionals in action</h3>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="/mychem/mylive">
                            <span class="ca-icon">В</span>
                            <div class="ca-content">
                                <h2 class="ca-main">Моя жизнь</h2>
                                <h3 class="ca-sub">Professionals in action</h3>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="/mychem/cpanel">
                            <span class="ca-icon">В</span>
                            <div class="ca-content">
                                <h2 class="ca-main">Контрол панель</h2>
                                <h3 class="ca-sub">Professionals in action</h3>
                            </div>
                        </a>
                    </li>                                    
                </ul>